### PR TITLE
Ben/get it running

### PR DESCRIPTION
**Pull request by warrenbhw**

### CODE REVIEW

**Comment by warrenbhw** [comment]
ignore this PR - accidental! Was just messing around trying to test out your repo :)

**Comment by arontsang** [comment]
@warrenbhw Any good?

**Comment by warrenbhw** [comment]
Yeah, you made an excellent start on this. Was able to get a variant working in my solidJS app

**Comment by warrenbhw** [comment]
I'm just getting started with AG grid, and I think the next thing I want to figure out is virtualizing the table (paging the query + rendering only what's in the viewport, if that's not already happening)

Ex: when I use a 10M row CSV as a source, everything works, but there is a bit more latency, which I'd like to reduce

**Comment by arontsang** [comment]
@warrenbhw feel free to PR any changes back in
This is a reimplementation of code I wrote at my job.

**Comment by arontsang** [comment]
@warrenbhw AG grid is already paging/virtualizing. CSV is not the best datasource, you should try parquet.
Additionally, this is mostly for analytics/pivoting.

**Comment by warrenbhw** [comment]
@arontsang thanks for the info & heads up :)

Are you using this in production, or is this just a side project for you?

**Comment by arontsang** [comment]
@warrenbhw [AdeelK93](https://github.com/AdeelK93) Managed to find a bug in the first pagination.
Try a git pull.
Unfortunately my team uses an old version of AgGrid, so, no, not in production.

**Comment by arontsang** [comment]
@warrenbhw You should take a look at this option on `GridOption` https://www.ag-grid.com/javascript-data-grid/server-side-model-configuration/#block-loading-debounce
This should make scrolling much more responsive when scrolling a huge csv

**Comment by warrenbhw** [comment]
This looks great. Thanks for sharing 🙏

**Comment by warrenbhw** [comment]
Are you guys actively using duckdb-datasource? If so, I'm happy to contribute back.

I haven't made many significant modifications yet, but I've done a few small things, such as identifier and value quoting/escaping to handle names with spaces and special characters

**Comment by warrenbhw** [comment]
I'm also an older AG grid version btw. Currently on 31.1.1 because I'm using solidJS and that's the last version with Solid support. Planning to update the community Solid lib at some point to get up to the latest AG grid version, but haven't had time yet

**Comment by arontsang** [comment]
v23.1.1.... :cry:

**Comment by arontsang** [comment]
> Are you guys actively using duckdb-datasource? If so, I'm happy to contribute back.
> 
> I haven't made many significant modifications yet, but I've done a few small things, such as identifier and value quoting/escaping to handle names with spaces and special characters

Could you create a PR to add your fixes?

**Comment by warrenbhw** [comment]
@arontsang yep definitely. I'm don't have the datasource code very cleanly separated from the rest of my application code rn, and we're super busy over the next couple weeks. Will try to get a PR up sometime in the next week...

if I'm not able to find the time, I'll contribute back any changes during first week of October at the latest.

**Comment by warrenbhw** [comment]
Are you down to turn this repo into an npm package? I think that'd help ensure that any users are working off of the same codebase and motivated to upstream their contribs

**Pull request closed without merging**
